### ISSUE TITLE
Can't able run own matcher node(waves-dex_2.0.3 with waves_1.1.10) receiving error

### ISSUE THREAD

**Issue by osiz-blockchainapp** [wavesplatform/matcher#288]
**Describe the bug**
Installed waves_1.1.10 , configured, and run the waves node. After installed the waves-dex.deb and configured and started waves-dex service it throws the **waves Node cannot be reached via gRPC**. 

**Expected behavior**
dex node should work. I just expect to see working Matcher REST API at port 6886.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
-  Version: waves-dex_2.0.3 , waves_1.1.10

**Screenshots:**
**Error:**
`Jun 05 10:25:52 ip-172-31-78-77 systemd[1]: Started DEX.
Jun 05 10:25:55 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:25:55,059 INFO  [main] c.w.dex.Application$ - Starting...
Jun 05 10:25:55 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:25:55,679 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
Jun 05 10:25:56 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:25:56,043 INFO  [main] c.w.dex.Application$ - DEX v2.0.3 Blockchain Id: W
Jun 05 10:25:56 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:25:56,134 INFO  [main] c.w.d.g.i.WavesBlockchainClientBuilder$ - Building gRPC client for server: 127.0.0.1:6869
Jun 05 10:26:01 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:01,194 INFO  [main] c.w.dex.Matcher - The DEX's public key: EnpqD41v3vtGErB9TwhJA1JbkwzZJfXrKKGdt5UPqa61, account address: 3P9fZrXbugNpNx9K4SC7b7nYZxnBqU9BCs1
Jun 05 10:26:01 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:01,331 INFO  [main] c.w.dex.Matcher - Events will be stored locally
Jun 05 10:26:01 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:01,353 INFO  [main] c.w.d.q.LocalMatcherQueue - Choosing com.wavesplatform.dex.queue.LocalMatcherQueue$LocalProducer producer
Jun 05 10:26:01 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:01,402 INFO  [ecution-context-global-24] c.w.dex.Matcher - Loading known assets ...
Jun 05 10:26:01 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:01,404 INFO  [ecution-context-global-24] c.w.dex.Matcher - Checking matcher's account script ...
Jun 05 10:26:01 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:01,482 INFO  [ecution-context-global-24] c.w.dex.Matcher - Initializing HTTP ...
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]: 2020-06-05 10:26:02,032 ERROR [a.actor.grpc-dispatcher-9] c.w.d.g.i.c.AssetDescriptionsCache - Error while value loading occurred:
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]: com.wavesplatform.dex.grpc.integration.exceptions.WavesNodeConnectionLostException: Waves Node cannot be reached via gRPC
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at com.wavesplatform.dex.grpc.integration.clients.WavesBlockchainGrpcAsyncClient.gRPCErrorsHandler(WavesBlockchainGrpcAsyncClient.scala:42)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at com.wavesplatform.dex.grpc.integration.clients.WavesBlockchainGrpcAsyncClient.$anonfun$handlingErrors$2(WavesBlockchainGrpcAsyncClient.scala:46)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.concurrent.Future.$anonfun$transform$3(Future.scala:245)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.concurrent.Future.$anonfun$transform$1(Future.scala:245)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at java.lang.Thread.run(Thread.java:748)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]: Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at io.grpc.Status.asRuntimeException(Status.java:530)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Jun 05 10:26:02 ip-172-31-78-77 waves-dex[5763]:     `

**Comment by msmolyakov** [comment]
Moved your issue to the dex matcher repository

**Comment by vsuharnikov** [comment]
The most interesting parts of log here are:
```
2020-06-05 10:25:56,134 INFO [main] c.w.d.g.i.WavesBlockchainClientBuilder$ - Building gRPC client for server: 127.0.0.1:6869
...
2020-06-05 10:26:02,032 ERROR [a.actor.grpc-dispatcher-9] c.w.d.g.i.c.AssetDescriptionsCache - Error while value loading occurred:
com.wavesplatform.dex.grpc.integration.exceptions.WavesNodeConnectionLostException: Waves Node cannot be reached via gRPC
```

Do you have a NODE with DEX Extension at 127.0.0.1:6869?

https://github.com/wavesplatform/matcher#61-node-installation

**Comment by osiz-blockchainapp** [comment]
Yes, I have waves node. Before starting the waves-dex Extension service installed [https://github.com/wavesplatform/Waves/releases/download/v1.1.10/waves_1.1.10_all.deb](url) and configured then started own waves node. 

After getting rest API calls at 127.0.0.1:6869 then installed 
[https://github.com/wavesplatform/matcher/releases/download/v2.0.3/waves-dex_2.0.3_all.deb](url) and configured then started waves-dex extension then it throws that error.

 Configuration files details
**Waves Conf File**  (/usr/share/waves/conf/waves.conf)
`waves {
  directory = ${user.home}"/waves"                              # replaced to /data
  data-directory = ${waves.directory}"/data"
  leveldb-cache-size = 256M
  network {
    file = ${waves.directory}"/peers.dat"
    bind-address = "[::]"       # IPv6
    bind-address = "0.0.0.0" # IPv4
    known-peers = [
      "13.228.86.201:6868",   "13.229.0.149:6868",  "18.195.170.147:6868",  "34.253.153.4:6868"
      "35.156.19.4:6868", "52.50.69.247:6868",  "52.52.46.76:6868",  "52.57.147.71:6868", "52.214.55.18:6868",  "54.176.190.226:6868"    ]
    peers-data-residence-time = 1d
    black-list-residence-time = 15m
    max-inbound-connections = 30
    max-outbound-connections = 30
    max-single-host-connections = 3
    connection-timeout = 30s
    max-unverified-peers = 100
    enable-peers-exchange = yes
    enable-blacklisting = yes
    peers-broadcast-interval = 2m
    handshake-timeout = 30s
suspension-residence-time = 1m
    upnp {
      enable = yes
      gateway-timeout = 7s
      discover-timeout = 3s
    }
    traffic-logger {
      ignore-tx-messages = [23, 25] # BlockMessageSpec, TransactionMessageSpec
      ignore-rx-messages = [25] # TransactionMessageSpec
    }
  }
  wallet {
    file = ${waves.directory}"/wallet/wallet.dat"
password = "YYYYYYYY"
seed ="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
blockchain {
    max-transactions-per-block-diff = 6000
    min-blocks-in-memory = 100
    type = MAINNET                      #replaced from
    }
  rest-api {
    enable = yes
    bind-address = "[::]"       # IPv6
    bind-address = "0.0.0.0" # IPv4
    port =6869
    api-key-hash = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
     cors = yes
    api-key-different-host = no
  }
synchronization {
    max-rollback = 100
    max-chain-length = 101
    synchronization-timeout = 60s
    score-ttl = 90s
    remote-score-debounce = 1s
    invalid-blocks-storage {
      max-size = 30000
      timeout = 1d
    }
    history-replier {
      max-micro-block-cache-size = 50
      max-block-cache-size = 20
    }
    utx-synchronizer {
      network-tx-cache-size = 1000000
      network-tx-cache-time = 10s
      max-buffer-size = 500
      max-buffer-time = 100ms
    }
    micro-block-synchronizer {
      wait-response-timeout = 2s
      processed-micro-blocks-cache-timeout = 3m
      inv-cache-timeout = 45s
    }  }
  utx {
    max-size = 100000
    max-transaction-age = 90m
    cleanup-interval = 5m
    blacklist-sender-addresses = []
    allow-blacklisted-transfer-to = []
  }
 features {
    auto-shutdown-on-unsupported-feature = yes
    supported = [1, 2 , 3]
  }
}
 waves.extensions = [ "com.wavesplatform.api.grpc.GRPCServerExtension"
     # "com.wavesplatform.dex.grpc.integration.DEXExtension"
]
waves.dex {
  # gRPC integration settings for Waves Node
  grpc.integration {
    host = "127.0.0.1" # "0.0.0.0" if the Matcher server connects to the Matcher extension from other machine
    port = 6886
  }
  price-assets = [
    "WAVES",
    "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS",
    "FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj",
    "944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg",
    "8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt",
]
    predefined-pairs = [
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "WAVES"},
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj"}
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg"},
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt"},

      {amountAsset = "WAVES", priceAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"},
      {amountAsset = "WAVES", priceAsset = "FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj"}
      {amountAsset = "WAVES", priceAsset = "944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg"},
      {amountAsset = "WAVES", priceAsset = "8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt"},
]}
include "local.conf"
`
**waves-dex conf file** (usr/share/waves-dex/conf/main.conf)

`
waves.dex {
  root-directory = "/var/lib/waves-dex"
  address-scheme-character = "W" # T - testnet, D - devnet, S - stagenet

  account-storage {
    type = "encrypted-file"
    encrypted-file {
      path = "/var/lib/waves-dex/account.dat"
      password = "YYYYYY"
    }
  }
  rest-api {
    # address = "0.0.0.0" # uncomment this line to accept connections from any host
    port = 6886
    api-key-hash = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    cors = yes
    api-key-different-host = no
  }
waves-blockchain-client.grpc.target = "127.0.0.1:6869"
  waves-blockchain-client {
    grpc {
      # target = "node.domain:6870"
    }
    default-caches-expiration = 100ms
  price-assets = [
    "WAVES",    "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS","FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj",
    "944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg",    "8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt",
]
    predefined-pairs = [
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "WAVES"},
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj"}
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg"},
      {amountAsset = "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS", priceAsset = "8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt"},

  ]
  allowed-asset-pairs=  [
    "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS-WAVES",
    "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS-FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj",
    "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS-944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg",
    "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS-8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt",]
}
`

**Comment by vsuharnikov** [comment]
I see:
* Waves NODE https://github.com/wavesplatform/Waves/releases/download/v1.1.10/waves_1.1.10_all.deb
* Matcher Server https://github.com/wavesplatform/matcher/releases/download/v2.0.3/waves-dex_2.0.3_all.deb

But there is no extension for NODE. Have you installed https://github.com/wavesplatform/matcher/releases/download/v2.0.3/waves-dex-extension_2.0.3_all.deb on the server with Waves NODE?

You will see in the NODE's logs 
```
gRPC DEX extension was bound to
```
If you installed it

**Comment by osiz-blockchainapp** [comment]
The node and matcher restApi was enabled and current my waves node height is 485200.

I can't able to access the matcher API call at (127.0.0.1:6886). I can able to access the matcher API once the full node gets synchronized?
And I can access the API only after full node synch?

**Comment by vsuharnikov** [comment]
1. You can access to make some basic checks, but anyway you have to wait the synchronization. Otherwise some new assets will be unavailable
2. Did you install `waves-dex-extension_2.0.3_all.deb` ? It is critical

**Comment by osiz-blockchainapp** [comment]
>     1. You can access to make some basic checks, but anyway you have to wait the synchronization. Otherwise some new assets will be unavailable
> 
>     2. Did you install `waves-dex-extension_2.0.3_all.deb` ? It is critical since `2.0.0`
Yes i installed it. wating for synchronization get done.

**Comment by vsuharnikov** [comment]
Seems you have wrong settings :)

The Waves NODE config:
```hocon
// ...
waves.dex {
  grpc.integration {
    host = "127.0.0.1"
    port = 6886 // Here is a port which exposes the data for Matcher server. Replace to 6887
  }
}
// ...
```

The matcher config:
```hocon
waves.dex {
  // ... 
  rest-api {
    // ...
    port = 6886 // Here is a HTTP port for clients
    // ...
  }
  waves-blockchain-client.grpc.target = "127.0.0.1:6869" // Here is a host:port to which Matcher server connects to get the data from the Waves NODE. Replace to "127.0.0.1:6887"
```

**Comment by osiz-blockchainapp** [comment]
> Seems you have wrong settings :)
> 
> The Waves NODE config:
> 
> ```
> // ...
> waves.dex {
>   grpc.integration {
>     host = "127.0.0.1"
>     // Here is a port which exposes the data for Matcher server. Replace to 6887
>     port = 6886
>   }
> }
> // ...
> ```
> 
> The matcher config:
> 
> ```
> waves.dex {
>   // ... 
>   rest-api {
>     // ...
>     port = 6886 // Here is a HTTP port for clients
>     // ...
>   }
>   // Here is a host:port to which Matcher server connects to get the data from the Waves NODE.
>   // Replace to "127.0.0.1:6887"
>   waves-blockchain-client.grpc.target = "127.0.0.1:6869"
>   // ...
> ```

I have modified the following above changes in configuration files then I restarted waves node am receiving following logs.

> Jun 09 09:40:32 ip-172-31-78-77 systemd[1]: Started Waves node.
Jun 09 09:40:33 ip-172-31-78-77 waves[16501]: INFO  c.w.Application$ - Starting...
Jun 09 09:40:34 ip-172-31-78-77 waves[16501]: INFO  a.event.slf4j.Slf4jLogger - Slf4jLogger started
Jun 09 09:40:34 ip-172-31-78-77 waves[16501]: INFO  c.w.Application$ - Waves v1.1.10 Blockchain Id: W
Jun 09 09:40:40 ip-172-31-78-77 waves[16501]: INFO  c.w.n.PeerDatabaseImpl - Loaded 154 known peer(s) from peers.dat
Jun 09 09:40:40 ip-172-31-78-77 waves[16501]: INFO  c.w.Application - Enable extension: com.wavesplatform.dex.grpc.integration.DEXExtension
Jun 09 09:40:41 ip-172-31-78-77 waves[16501]: INFO  c.w.Application - REST API was bound on 0.0.0.0:6869
Jun 09 09:40:42 ip-172-31-78-77 waves[16501]: INFO  c.w.d.g.i.DEXExtension - gRPC DEX extension was bound to /127.0.0.1:6887
Jun 09 09:40:50 ip-172-31-78-77 waves[16501]: INFO  c.w.n.HandshakeHandler$Client - [0b0330ff 35.156.19.4:6868] Accepted handshake Handshake(wavesW,(1,1,11),waves-official-eu-node-7,159913,Some(/35.156.19.4:6868))
Jun 09 09:40:56 ip-172-31-78-77 waves[16501]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 887200
Jun 09 09:41:00 ip-172-31-78-77 waves[16501]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 887300
Jun 09 09:41:02 ip-172-31-78-77 waves[16501]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 887400
Jun 09 09:41:05 ip-172-31-78-77 waves[16501]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 887500

 The node rest API was enabled at 127.0.0.1:6869. But the matcher  API not enabled  at 127.0.0.1:6887 but in logs  **- gRPC DEX extension was bound to /127.0.0.1:6887** . So how can I access the Matcher API calls.

**Comment by vsuharnikov** [comment]
http://127.0.0.1:6886 if your config contains such lines:
```
waves.dex {
  // ... 
  rest-api {
    // ...
    port = 6886 // Here is a HTTP port for clients
```

**Comment by osiz-blockchainapp** [comment]
> http://127.0.0.1:6886 if your config contains such lines:
> 
> ```
> waves.dex {
>   // ... 
>   rest-api {
>     // ...
>     port = 6886 // Here is a HTTP port for clients
> ```

Yes, I config Matcher API at 6886. 
In old waves(1.1.6) node with matcher(v1.0.4) node setting when I start the waves node after configuring the matcher node it shows the node API enabled at 6869 and Matcher Api enabled at 6886.
But I am not getting the Matcher API address in these logs and also I can't able access the Matcher API at 6886.

**Comment by vsuharnikov** [comment]
Things are changed heavy in 2.0.0. There are more detailed description of changes and some migration steps: https://github.com/wavesplatform/matcher/releases/tag/v2.0.0

> I can't able access the Matcher API at 6886

It is unaccessible outside or from the server too? Have you tried `curl http://127.0.0.1:6886/matcher` from the server with Matcher?

**Comment by osiz-blockchainapp** [comment]
> Is it unaccessible outside or from the server too? Have you tried `curl http://127.0.0.1:6886/matcher` from the server with Matcher?
 
It's unaccessible from the server itself and outside too. 
curl response is
> curl: (7) Failed to connect to 127.0.0.1 port 6886: Connection refused

**Comment by vsuharnikov** [comment]
Hm... have you restarted `waves-dex` service after last config changes?

**Comment by osiz-blockchainapp** [comment]
> Hm... have you restarted `waves-dex` service after last config changes?

yes, after restarting waves-dex service am receiving following below logs 

> Started DEX.
Jun 10 09:44:31 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:31,074 INFO  [main] c.w.dex.Application$ - Starting...
Jun 10 09:44:31 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:31,653 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
Jun 10 09:44:32 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:32,280 INFO  [main] c.w.dex.Application$ - DEX v2.0.3 Blockchain Id: W
Jun 10 09:44:32 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:32,450 INFO  [main] c.w.d.g.i.WavesBlockchainClientBuilder$ - Building gRPC client for server: 127.0.0.1:6887
Jun 10 09:44:40 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:40,110 INFO  [main] c.w.dex.Matcher - The DEX's public key: EnpqD41v3vtGErB9TwhJA1JbkwzZJfXrKKGdt5UPqa61, account address: 3P9fZrXbugNpNx9K4SC7b7nYZxnBqU9BCs1
Jun 10 09:44:40 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:40,237 INFO  [main] c.w.dex.Matcher - Events will be stored locally
Jun 10 09:44:40 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:40,244 INFO  [main] c.w.d.q.LocalMatcherQueue - Choosing com.wavesplatform.dex.queue.LocalMatcherQueue$LocalProducer producer
Jun 10 09:44:40 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:40,265 INFO  [ecution-context-global-24] c.w.dex.Matcher - Loading known assets ...
Jun 10 09:44:40 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:40,267 INFO  [ecution-context-global-24] c.w.dex.Matcher - Checking matcher's account script ...
Jun 10 09:44:40 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:40,363 INFO  [ecution-context-global-24] c.w.dex.Matcher - Initializing HTTP ...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,150 ERROR [ecution-context-global-24] c.w.dex.Matcher - Can't load assets: 944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg, 8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt, FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj. Try to sync up your node with the network.
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,155 INFO  [shutdownHook3] c.w.dex.Application - Shutting down initiated
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,155 INFO  [shutdownHook3] c.w.dex.Application - Shutting down reporters...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,160 INFO  [shutdownHook3] c.w.dex.Matcher - Status now is Stopping
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,161 INFO  [shutdownHook3] c.w.dex.Matcher - Shutting down HTTP server...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,162 INFO  [ecution-context-global-26] c.w.dex.Application - Reporters stopped
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,169 INFO  [ecution-context-global-26] c.w.dex.Matcher - Shutting down actors...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,192 INFO  [ctor.default-dispatcher-7] c.w.d.market.MatcherActor - Recovery completed!
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,233 INFO  [ecution-context-global-26] c.w.dex.Matcher - Shutting down gRPC client...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,260 INFO  [ecution-context-global-26] c.w.dex.Matcher - Shutting down queue...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,262 INFO  [ecution-context-global-26] c.w.dex.Matcher - Shutting down caches...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,263 INFO  [ecution-context-global-26] c.w.dex.Matcher - Shutting down materializer...
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,267 INFO  [ecution-context-global-26] c.w.dex.Matcher - Matcher stopped
Jun 10 09:44:41 ip-172-31-78-77 waves-dex[20790]: 2020-06-10 09:44:41,269 INFO  [ecution-context-global-26] c.w.dex.Application - Shutdown complete

**Comment by vsuharnikov** [comment]
From logs:
```
Can't load assets: 
944R5BhatCh77eG3CxWyi1RdVW5vdNXkPa42HB11GhFg,
8jNCw2kxZeq2ujZcTZ9HqMbMmJteoaJnjaxxP58ne8wt, 
FhmfyYuYXoecWCr8B6xJKp7XtBUsYWFc5H5angvhEgLj

Try to sync up your node with the network.
```

Well, let's wait for synchronization :)

**Comment by vsuharnikov** [comment]
How are you? You could just import the blockchain, there is no reason to wait for a network sync :)

**Comment by vsuharnikov** [comment]
Any changes? @osiz-blockchainapp

**Comment by osiz-blockchainapp** [comment]
Hi, Sorry for the delayed reply. I am fine How are you?

My waves node height is now 1766177. can I import the remaining block?

**Comment by vsuharnikov** [comment]
Sure, your node will skip blocks that have and import only remaining, see https://docs.wavesprotocol.org/en/waves-node/options-for-getting-actual-blockchain/import-from-the-blockchain#import-blockchain-from-binary-file

**Comment by osiz-blockchainapp** [comment]
Hi, How are you? 

Again my waves node has stoped after this block 2139133 and recieving the follwing logs. 

![2](https://user-images.githubusercontent.com/48212011/88398283-cd5dc900-cde2-11ea-9df0-9eef5ca2f76b.png)

What is the error? why node is not synchronizing? what is the solution for this?

**Comment by vsuharnikov** [comment]
Have no idea, try to ask [them](https://github.com/wavesplatform/Waves/issues/new?assignees=phearnot&labels=bug&template=bug_report.md&title=) NODE developers ;)

Well, looks like there are no issues with the Matcher part, I'll close the issue.
