### ISSUE TITLE
[BUG] Docker container documentation mismatch

### ISSUE THREAD

**Issue by anatolll** [wavesplatform/matcher#536]
I want to run a matcher in a docker container.
In the document https://github.com/wavesplatform/matcher/blob/v2.3.2.1/dex/README_DOCKER.md I see references to wavesplatform/matcher-node and wavesplatform/matcher-server containers. However, these containers are not listed on dockerhub, or access to them is denied.
Tell me how you can access these containers.

Thank you

**Comment by vsuharnikov** [comment]
It is not possible right now. We haven't tested them yet, so we don't publish them.
